services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pautaservice
      MYSQL_DATABASE: votacao_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - votacao_network

  spring:
    image: openjdk:17-jdk
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/votacao_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pautaservice
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - votacao_network

volumes:
  mysql_data:

networks:
  votacao_network:
